[book]
authors = [
    "a-vrma",
    "cshmnyfy",
    "FichteFoll",
    "kageru",
    "LightArrowsEXE",
    "Lypheo",
    "OrangeChannel",
    "rokweom",
    "shssoichiro",
    "stuxcrystal",
    "Velvetine",
    "ILOVEPIE"
]
language = "en"
multilingual = false
src = "src"

[build]
create-missing = false

[output.html]
default-theme = "navy"
curly-quotes = true
mathjax-support = true
# additional-css = [""]
git-repository-url = "https://github.com/Irrational-Encoding-Wizardry/guide.encode.moe"
